ChannelName = "#"
ServerName = "irc.chat.twitch.tv:6667"
# Oauth from Twitch here
BotOAuth = "oauth:"
BotName = ""

WebAppGUIEnabled = false #If true, server / GUI component of HappyBot will be enabled.

##### POINTS #####
PointsSystemEnabled = false
PointsValueModifier = 3 # Each user will get this amount of points per increment.
PointsIncrementTime = 10 # How many seconds the bot should hand out points in seconds.
PointsMessage = "@{target}, you have {value} points." # Use {target} to refer to user, and {value} to the points amount.

##### CHAT PROPERTIES #####
LetModeratorsUseAllCommands = true # This allows a moderator to use any command, including broadcaster specific commands.

# When you wish to refer to the promoted caster, type in 'target' and their username will be replaced accordingly by the bot.
CasterMessage = "Follow @{target} for some awesome content! https://www.twitch.tv/{target}"

CheckLongMessageCap = true
LongMessageCap = 300

StreamerTimeToggle = true # Toggle whether !time, !uptime is enabled or not

MakeLog = false  # Disabled by default, logs can take up space fast depending on chat activity

RespondToSubs = true
SubResponse = "thanks for subscribing!"

PurgeForLinks = true
LinkChecks = [".com", ".net", ".org", ".tv"]

HydrateOn = false
HydrateTime = 30 # In minutes, how often you want to be reminded to hydrate!
HydrateMessage = "It's hydrating time!"