# Put in your channel name, please keep the # symbol there.
ChannelName = "#"
ServerName = "irc.chat.twitch.tv:6667"
# Oauth from Twitch here
BotOAuth = ""
# Bot Twitch Account name here: keep # there.
BotName = "#"