ChannelName = "#lphm"
ServerName = "irc.chat.twitch.tv:6667"
# Oauth from Twitch here
BotOAuth = "oauth:g438gb4qn6fnhhevoofl3qzrtoxwh7"
BotName = "#"
##### CHAT PROPERTIES #####
LetModeratorsUseAllCommands = true # This allows a moderator to use any command, including broadcaster specific commands.

CheckLongMessageCap = true
LongMessageCap = 300

StreamerTimeToggle = true # Toggle whether !time is enabled or not

MakeLog = false  # Disabled by default, logs can take up space fast depending on chat activity

SubResponse = "thanks for subscribing!"

PurgeForLinks = true
LinkChecks = [".com", ".net", ".org"]