ChannelName = "#"
ServerName = "irc.chat.twitch.tv:6667"
# Oauth from TWitch here
BotOAuth = ""
BotName = "#"
##### CHAT PROPERTIES #####
CheckLongMessageCap = true
LongMessageCap = 300

StreamerTimeToggle = false # Toggle whether !time is enabled or not

MakeLog = false  # Disabled by default, logs can take up space fast depending on chat activity

SubResponse = "thanks for subscribing!"

PurgeForLinks = true
LinkChecks = [".com", ".net", ".org"]