ChannelName = "#"
ServerName = "irc.chat.twitch.tv:6667"
# Oauth from Twitch here
BotOAuth = "oauth:"
BotName = ""

WebAppGUIEnabled = false #If true, server / GUI component of HappyBot will be enabled.

##### POINTS #####
PointsSystemEnabled = true
PointsName = "points" #Use this to change the command users can type to see the points they have. Examples: !euros, !gold
PointsValueModifier = 3 # Each user will get this amount of points per increment.
PointsIncrementTime = 120 # How many seconds the bot should hand out points in seconds.
PointsMessage = "@{target}, you have {value} {currency}." # Use {target} to refer to user, and {value} to the points amount.

##### GAME PROPERTIES #####
GamesEnabled = true 

## Roulette ##
RouletteEnabled = true
RouletteWinMessages = ["Dang, it's your lucky day! @{target} just got {value} {currency}!", "A true display of valor. @{target} just won {value} {currency}!"] # Write as many possible win statements here. The bot will choose a random one! :)
RouletteLossMessages = ["A sad day indeed... {target} just lost {value} {currency}.", "Luck was not on the cards today. @{target} just lost {value} {currency}."]

##### CHAT PROPERTIES #####
LetModeratorsUseAllCommands = true # This allows a moderator to use any command, including broadcaster specific commands.

# When you wish to refer to the promoted caster, type in '{target}' and their username will be replaced accordingly by the bot.
CasterMessage = "Follow @{target} for some awesome content! https://www.twitch.tv/{target}"

CheckLongMessageCap = true
LongMessageCap = 300

StreamerTimeToggle = true # Toggle whether !time, !uptime is enabled or not

MakeLog = false  # Disabled by default, logs can take up space fast depending on chat activity

RespondToSubs = true
SubResponse = "thanks for subscribing!"

PurgeForLinks = true
LinkChecks = [".com", ".net", ".org", ".tv"]

HydrateOn = false
HydrateTime = 30 # In minutes, how often you want to be reminded to hydrate!
HydrateMessage = "It's hydrating time!"